apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snipeit-storage
  namespace: snipeit
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi
