apiVersion: apps/v1
kind: Deployment
metadata:
  name: snipeit
  namespace: snipeit
  labels:
    app: snipeit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snipeit
  template:
    metadata:
      labels:
        app: snipeit
    spec:
      securityContext:
        fsGroup: 1000  # Menyamakan grup agar akses NFS lancar
      containers:
      - name: snipeit
        image: snipe/snipe-it:v8.3.7
        env:
        - name: TZ
          value: "Asia/Jakarta"
        - name: SESSION_DRIVER
          value: redis
        - name: CACHE_DRIVER
          value: redis
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: APP_URL
          value: "https://plaset.it-ops.my.id"  # Ganti dengan IP Ingress nanti
        - name: TRUSTED_PROXIES
          value: "*"
        - name: DB_HOST
          value: "192.168.10.155"
        - name: DB_DATABASE
          value: "snipeit"
        - name: DB_USERNAME
          value: "snipeit"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: snipeit-secret
              key: db-password
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: snipeit-secret
              key: app-key
        volumeMounts:
        - name: snipeit-data
          mountPath: /var/lib/snipeit  # Path yang benar untuk image linuxserver/snipe-it
      volumes:
      - name: snipeit-data
        persistentVolumeClaim:
          claimName: snipeit-pvc
