apiVersion: v1
kind: PersistentVolume
metadata:
  name: snipeit-nfs-pv
spec:
  capacity:
    storage: 20Gi  # Sesuaikan dengan kebutuhan storage Anda
  accessModes:
    - ReadWriteMany  # Mode ini penting agar bisa dibaca-tulis banyak pod
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.60  # IP NFS server Anda
    path: /srv/nfs/snipeit  # Pastikan path ini sudah dibuat di NFS server
