apiVersion: v1
kind: PersistentVolume
metadata:
  name: snipeit-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.60
    path: /srv/nfs/snipeit
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snipeit-pvc
  namespace: snipeit
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
