apiVersion: v1
kind: Service
metadata:
  name: snipeit-service
  namespace: snipeit
spec:
  selector:
    app: snipeit
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP  # Cukup diakses internal oleh cloudflared
