apiVersion: v1
kind: PersistentVolume
metadata:
  name: snipeit-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.10.60
    path: /srv/nfs/snipeit
