apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snipeit-pvc
  namespace: snipeit
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 20Gi
